name: Mirror to Ebrains

on:
  push:
    branches: [master]
    tags:
      - "*"

jobs:
  to_ebrains:
    runs-on: ubuntu-latest
    steps:
      - name: syncmaster
        uses: wei/git-sync@55c6b63b4f21607da0e9877ca9b4d11a29fc6d83 #v3.0.0
        with:
          source_repo: "Medical-Informatics-Platform/platform-ui"
          source_branch: "master"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/hbp-mip/platform-ui.git"
          destination_branch: "master"
      - name: synctags
        uses: wei/git-sync@55c6b63b4f21607da0e9877ca9b4d11a29fc6d83 #v3.0.0
        with:
          source_repo: "Medical-Informatics-Platform/platform-ui"
          source_branch: "refs/tags/*"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/hbp-mip/platform-ui.git"
          destination_branch: "refs/tags/*"
