name: Static Application Security Testing (SAST)

on:
  push: # To be removed after testing
  pull_request:
  workflow_dispatch:

jobs:
  sast:
    name: Static Application Security Testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # required for uploading SAST results to github security
    env:
      SEMGREP_CONFIGS: "p/security-audit p/owasp-top-ten p/cwe-top-25 p/trailofbits p/java"
      SEMGREP_EXCLUDE: ".github Dockerfile* target/** dist/** build/** node_modules/** .angular/**"
      SEMGREP_SARIF_OUTPUT: sast-semgrep-app.sarif
      SAST_SEVERITY: ERROR
      SAST_ENFORCE: "false"

    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 #v6.2.0
        with:
          python-version: '3.14.4'

      - name: Setup tools
        run: bash .github/scripts/setup-tools.sh --install-tool opengrep

      - name: Run SAST scanning
        run: python .github/scripts/sast_scan.py

      - name: Upload Semgrep SARIF to GitHub Security tab
        id: upload_semgrep
        if: always()
        uses: github/codeql-action/upload-sarif@c35d1b164463ee62a100735382aaaa525c5d3496 #v2.25.6
        with:
          sarif_file: ${{ env.SEMGREP_SARIF_OUTPUT }}
          category: semgrep-app

      - name: Upload SARIF artifact
        if: ${{ always() && steps.upload_semgrep.outcome == 'success' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: sast-scan-sarif-report
          path: ${{ env.SEMGREP_SARIF_OUTPUT }}
          retention-days: 30