name: SCA CI - image

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1' # weekly SCA scan, every Monday 02:00 UTC

jobs:
  sca:
    name: Software Composition Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # required for uploading SCA results to github security
    env:
      IMAGE_NAME: platform-ui:testing
      TRIVY_IGNOREFILE: .github/scripts/suppress_trivy.yaml
      OSV_IGNOREFILE: .github/scripts/suppress_osv_scanner.toml
      TRIVY_SARIF_OUTPUT: trivy-image.sarif
      OSV_SARIF_OUTPUT: osv-scanner-image.sarif
      MERGED_SARIF_OUTPUT: merged-SCA-platform-ui-image.sarif
    
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 #v6.3.0
        with:
          # renovate: datasource=python-version depName=python
          python-version: '3.14.4'

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Setup tools
        run: bash .github/scripts/setup-tools.sh

      - name: Run SCA tools
        run: python .github/scripts/run_sca_image.py

      - name: Upload Trivy SARIF to GitHub Security tab
        id: upload_trivy
        if: always()
        uses: github/codeql-action/upload-sarif@c35d1b164463ee62a100735382aaaa525c5d3496 #v2.25.6
        with:
          sarif_file: ${{ env.TRIVY_SARIF_OUTPUT }}
          category: trivy-sca-image

      - name: Upload OSV Scanner SARIF to GitHub Security tab
        id: upload_osv
        if: always()
        uses: github/codeql-action/upload-sarif@c35d1b164463ee62a100735382aaaa525c5d3496 #v2.25.6
        with:
          sarif_file: ${{ env.OSV_SARIF_OUTPUT }}
          category: osv-sca-image

      - name: Upload merged SARIF to GitHub Security tab
        if: ${{ always() && steps.upload_trivy.outcome == 'success' && steps.upload_osv.outcome == 'success' }}
        uses: github/codeql-action/upload-sarif@c35d1b164463ee62a100735382aaaa525c5d3496 #v2.25.6
        with:
          sarif_file: ${{ env.MERGED_SARIF_OUTPUT }}
          category: merged-sca-image